name: Build Single Header

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run build script
        run: python single_header/build.py

      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add single_header/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto-update single_header after push"
            git push
          fi
